const actions = {
  BUILD_ANIMATION: 'BUILD_ANIMATION',
  CLEAN_ANIMATION: 'CLEAN_ANIMATION',
  SET_ALGORITHM: 'SET_ALGORITHM',
  SET_ANIMATION_FINISHED: 'SET_ANIMATION_FINISHED',
  SET_BARS: 'SET_BARS',
  SET_BARS_HEIGHT: 'SET_BARS_HEIGHT',
  SET_BAR_BY_IDX: 'SET_BAR_BY_IDX',
  SET_NAVBAR_BUTTONS_DISABLED: 'SET_NAVBAR_BUTTONS_DISABLED',
  SET_RUN_ALGORITHM: 'SET_RUN_ALGORITHM',
  SET_SPEED: 'SET_SPEED',
};

export default actions;
